import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Provider from "./Context/Provider";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <div>
            <Navbar />
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
